codecov:
  branch: master

coverage:
  precision: 1
  range: "50...100"
  status:
    project:
      default:
        target: '85'
    patch:
      default:
        target: '75'
                  
comment:
  layout: header, changes, diff

